# Site settings
title: Endless Times
version: "v1"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: /:year/:title.html

# Tachyons Version
tv: "4.7.0"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag
